# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "nirae/ghidra_debian"
  
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true

    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
    end
end
  